"""
Anomaly injector for synthetic GPU power data.

This module provides a function to inject various types of anomalies into a
baseline GPU power time series generated by `src.data.generator.generate_power_series`.

Supported anomaly types:
- 'spike': a sudden positive jump at a single point.
- 'drop': a sudden negative jump at a single point.
- 'drift': a gradual linear change over a window.
- 'burst': a noisy burst with higher variance over a window.
- 'flatline': constant value over a window (power stops changing).

Each anomaly specification should include at least:
- 'type': one of the supported anomaly types.
- 'index': integer start index in the DataFrame (0-based).
- 'length': number of points affected (default is 1).
- 'amplitude': magnitude or scale of the anomaly (interpretation depends on type).

The function returns a new DataFrame with an additional boolean column 'anomaly'
marking rows where anomalies were injected.
"""

from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd


def inject_anomalies(
    df: pd.DataFrame,
    anomalies: List[Dict[str, Any]],
    seed: Optional[int] = None,
) -> pd.DataFrame:
    """
    Inject anomalies into a baseline GPU power time series.

    Parameters
    ----------
    df : pandas.DataFrame
        DataFrame containing at least a 'power' column to modify.
    anomalies : list of dict
        Each dict specifies an anomaly with keys:
        - 'type' (str): 'spike', 'drop', 'drift', 'burst', or 'flatline'.
        - 'index' (int): start index for the anomaly (0-based).
        - 'length' (int, optional): number of points (default 1).
        - 'amplitude' (float, optional): magnitude of the anomaly; meaning depends on type.
    seed : int or None, default None
        Random seed for reproducibility.

    Returns
    -------
    pandas.DataFrame
        A copy of the input DataFrame with an 'anomaly' boolean column indicating
        which rows were modified.
    """
    new_df = df.copy()
    new_df["anomaly"] = False

    if seed is not None:
        np.random.seed(seed)

    for spec in anomalies:
        a_type = spec.get("type")
        start_idx = int(spec.get("index", 0))
        length = int(spec.get("length", 1))
        amplitude = float(spec.get("amplitude", 0.0))

        end_idx = min(start_idx + length, len(new_df))

        if start_idx < 0 or start_idx >= len(new_df) or end_idx <= start_idx:
            continue

        if a_type == "spike":
            new_df.loc[start_idx, "power"] += amplitude
            new_df.loc[start_idx, "anomaly"] = True

        elif a_type == "drop":
            new_df.loc[start_idx, "power"] -= amplitude
            new_df.loc[start_idx, "anomaly"] = True

        elif a_type == "drift":
            drift = np.linspace(0.0, amplitude, end_idx - start_idx)
            new_df.loc[start_idx : end_idx - 1, "power"] += drift
            new_df.loc[start_idx : end_idx - 1, "anomaly"] = True

        elif a_type == "burst":
            base_std = new_df["power"].std(ddof=0)
            noise = np.random.normal(
                loc=0.0,
                scale=base_std * max(amplitude, 1.0),
                size=end_idx - start_idx,
            )
            new_df.loc[start_idx : end_idx - 1, "power"] += noise
            new_df.loc[start_idx : end_idx - 1, "anomaly"] = True

        elif a_type == "flatline":
            flat_value = new_df.loc[start_idx, "power"]
            new_df.loc[start_idx : end_idx - 1, "power"] = flat_value
            new_df.loc[start_idx : end_idx - 1, "anomaly"] = True

        else:
            continue

    return new_df